version: "3.8"

services:
  operonone:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: operonone-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATA_DIR=/app/data
    env_file:
      - .env
    volumes:
      # Mount Docker socket to allow container to use Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount data directory for persistence
      - ./data:/app/data
      # Mount output directory for user files
      - ./output:/app/output
    # Add docker group GID to allow Docker access
    group_add:
      - ${DOCKER_GID:-999}
    networks:
      - operonone-network

networks:
  operonone-network:
    driver: bridge
