version: "3.8"

services:
  operonone:
    image: ghcr.io/neooriginal/operonone:latest
    container_name: operonone-app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      # Required environment variables
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - JWT_SECRET=${JWT_SECRET:-operon-default-jwt-secret-change-in-production}

      # Application configuration
      - PORT=3000
      - DATA_DIR=/app/data

      # Optional: Email verification (if not set, email verification will be skipped)
      - SMTP_HOST=${SMTP_HOST:-}
      - SMTP_PORT=${SMTP_PORT:-}
      - SMTP_USER=${SMTP_USER:-}
      - SMTP_PASS=${SMTP_PASS:-}
      - SMTP_FROM=${SMTP_FROM:-}

      # Playwright configuration
      - PLAYWRIGHT_BROWSERS_PATH=/app/.playwright-browsers
      - PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=/usr/bin/chromium
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - operonone_data:/app/data
    user: "0:0"
    networks:
      - operonone-network
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))",
        ]
      interval: 30s
      timeout: 10s
      start_period: 40s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  operonone_data:
    driver: local

networks:
  operonone-network:
    driver: bridge
