version: "3.8"

services:
  operonone:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: operonone-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATA_DIR=/app/data
      - TRUST_PROXY=true
      - PLAYWRIGHT_BROWSERS_PATH=/app/.playwright-browsers
      - HTTP_TIMEOUT=60000
      - KEEP_ALIVE_TIMEOUT=65000
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - data_volume:/app/data
    user: "0:0"
    networks:
      - operonone-network

volumes:
  data_volume:
    driver: local

networks:
  operonone-network:
    driver: bridge
